/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AssetType, AuctionStatus, AuctionListing } from "./types";

export const ASSET_TYPE_COLORS: Record<AssetType, string> = {
  [AssetType.REAL_ESTATE]: "bg-blue-100 text-blue-700",
  [AssetType.VEHICLE]: "bg-purple-100 text-purple-700",
  [AssetType.MACHINERY]: "bg-orange-100 text-orange-700",
  [AssetType.FINANCIAL_ASSET]: "bg-emerald-100 text-emerald-700",
  [AssetType.OTHER]: "bg-neutral-100 text-neutral-700",
};

export const MOCK_AUCTIONS: AuctionListing[] = [
  {
    id: "1",
    title: "Prime Commercial Land in Kathmandu",
    description: "A 5000 sq. ft. commercial plot located in the heart of Kathmandu. Ideal for business centers or retail outlets.",
    assetType: AssetType.REAL_ESTATE,
    basePrice: 50000000,
    reservePrice: 55000000,
    currentBid: 52000000,
    bidCount: 12,
    startTime: new Date().toISOString(),
    endTime: new Date(Date.now() + 86400000 * 3).toISOString(),
    status: AuctionStatus.ACTIVE,
    location: {
      address: "Durbar Marg, Kathmandu",
      latitude: 27.7103,
      longitude: 85.3222,
    },
    institutionId: "inst1",
    institutionName: "Nepal Investment Bank",
    images: ["https://picsum.photos/seed/realestate1/800/600"],
    documents: [{ name: "Valuation Report", url: "#" }],
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "2022 Toyota Hilux - Repossessed",
    description: "Excellent condition, low mileage (15,000 km). Fully serviced and maintained by authorized dealer.",
    assetType: AssetType.VEHICLE,
    basePrice: 4500000,
    reservePrice: 4800000,
    currentBid: 4600000,
    bidCount: 8,
    startTime: new Date().toISOString(),
    endTime: new Date(Date.now() + 86400000 * 1).toISOString(),
    status: AuctionStatus.ACTIVE,
    location: {
      address: "Pokhara, Kaski",
      latitude: 28.2096,
      longitude: 83.9856,
    },
    institutionId: "inst2",
    institutionName: "Nabil Bank",
    images: ["https://picsum.photos/seed/vehicle1/800/600"],
    documents: [{ name: "Bluebook Copy", url: "#" }],
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Industrial Printing Press - Heidelberg",
    description: "High-capacity industrial printing press. Model 2018, well-maintained, currently in storage.",
    assetType: AssetType.MACHINERY,
    basePrice: 12000000,
    reservePrice: 13500000,
    currentBid: 12500000,
    bidCount: 5,
    startTime: new Date().toISOString(),
    endTime: new Date(Date.now() + 86400000 * 5).toISOString(),
    status: AuctionStatus.ACTIVE,
    location: {
      address: "Biratnagar, Morang",
      latitude: 26.4525,
      longitude: 87.2718,
    },
    institutionId: "inst3",
    institutionName: "Global IME Bank",
    images: ["https://picsum.photos/seed/machinery1/800/600"],
    documents: [{ name: "Technical Specs", url: "#" }],
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Corporate Bond Portfolio - 500 Units",
    description: "A portfolio of high-yield corporate bonds from various manufacturing sectors.",
    assetType: AssetType.FINANCIAL_ASSET,
    basePrice: 2000000,
    reservePrice: 2100000,
    currentBid: 2050000,
    bidCount: 15,
    startTime: new Date().toISOString(),
    endTime: new Date(Date.now() + 86400000 * 2).toISOString(),
    status: AuctionStatus.ACTIVE,
    location: {
      address: "Lalitpur, Bagmati",
      latitude: 27.6644,
      longitude: 85.3188,
    },
    institutionId: "inst1",
    institutionName: "Nepal Investment Bank",
    images: ["https://picsum.photos/seed/finance1/800/600"],
    documents: [{ name: "Prospectus", url: "#" }],
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Luxury Apartment in Sanepa",
    description: "3 BHK luxury apartment with modern amenities. 1800 sq. ft. area, 5th floor.",
    assetType: AssetType.REAL_ESTATE,
    basePrice: 35000000,
    reservePrice: 38000000,
    currentBid: 36000000,
    bidCount: 20,
    startTime: new Date().toISOString(),
    endTime: new Date(Date.now() + 86400000 * 10).toISOString(),
    status: AuctionStatus.ACTIVE,
    location: {
      address: "Sanepa, Lalitpur",
      latitude: 27.6784,
      longitude: 85.3012,
    },
    institutionId: "inst4",
    institutionName: "NIC Asia Bank",
    images: ["https://picsum.photos/seed/realestate2/800/600"],
    documents: [{ name: "Ownership Certificate", url: "#" }],
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Excavator - Caterpillar 320D",
    description: "Heavy-duty excavator, 2019 model. 4500 hours of operation. Ready for construction projects.",
    assetType: AssetType.MACHINERY,
    basePrice: 8500000,
    reservePrice: 9000000,
    currentBid: 8700000,
    bidCount: 3,
    startTime: new Date().toISOString(),
    endTime: new Date(Date.now() + 86400000 * 4).toISOString(),
    status: AuctionStatus.ACTIVE,
    location: {
      address: "Butwal, Rupandehi",
      latitude: 27.7006,
      longitude: 83.4484,
    },
    institutionId: "inst2",
    institutionName: "Nabil Bank",
    images: ["https://picsum.photos/seed/machinery2/800/600"],
    documents: [{ name: "Maintenance Log", url: "#" }],
    createdAt: new Date().toISOString(),
  }
];
